spring.application.name=api
server.port=${SERVER_PORT:8081}
app.reserva.multiplicador-hora-extra=${RESERVA_MULTIPLICADOR_HORA_EXTRA:1.5}

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/arena_vibe_volei?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
server port = 8081